import React from "react";
// 1. Import font từ next/font/google
import { Roboto } from "next/font/google";

// 2. Cấu hình font
const roboto = Roboto({
  weight: ["400", "700"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Lab 6 - Next.js Optimization",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* 3. Áp dụng className của font vào body */}
      <body className={roboto.className} style={{ margin: 0 }}>
        {children}
      </body>
    </html>
  );
}
